### ISSUE TITLE
"Key 'concurrency' is not allowed"

### ISSUE THREAD

**Issue by janpio** [cschleiden/vscode-github-actions#102]
Using `concurrency` in a job leads to unhappy results:
![image](https://user-images.githubusercontent.com/183673/121422007-0ce7c200-c96f-11eb-8fb3-c8608c25af60.png)

At the same time the documentation of it is shown just fine:
![image](https://user-images.githubusercontent.com/183673/121422087-2426af80-c96f-11eb-9f58-06781b42897d.png)

Via https://github.com/prisma/e2e-tests/blob/dev/.github/workflows/test.yaml

**Comment by cschleiden** [comment]
Fixed in 0.20.1 🎉.
