### ISSUE TITLE
Extension must be installed on remote, otherwise it does not work

### ISSUE THREAD

**Issue by tomaxsas** [cschleiden/vscode-github-actions#110]
There is something wrong with extension kind. By default it does not work in WSL or SSH, actions does not shows up in panel. When i forcefully install on remote, when extension is fully operational. so the target should be changed to workspace i guess.

**Comment by cschleiden** [comment]
This was last changed in https://github.com/cschleiden/vscode-github-actions/pull/105, @leighmcculloch do you know more about this?

**Comment by cschleiden** [comment]
I have reverted `extensionKind` to `workspace` for now. Thanks for reporting 🙇

**Comment by leighmcculloch** [comment]
It looks like when I tested this my setting didn't stick and was using the default setting still. Apologies.
