### ISSUE TITLE
feature request: show status check indicator for current checked out branch

### ISSUE THREAD

**Issue by Thatkookooguy** [cschleiden/vscode-github-actions#113]
related to #84 which was closed because of inactivity.

But this is till an issue.
The original description:
>When working on a specific branch inside vscode, only show the Pin workflows and see their status updates for the currently checked out branch.
>
>This is better for multi-user projects. I want to see the status checks of the work I'm doing atm, and not see what's up when ever a user pushes to a public branch.
>
>I'll try and implement this myself if I'll have the time. thanks for a great extension!

**Comment by cschleiden** [comment]
There is now the `Current Branch` view that provides that - at least in some form.
