### ISSUE TITLE
Pinned workflow should also refresh in TreeView

### ISSUE THREAD

**Issue by JustinGrote** [cschleiden/vscode-github-actions#114]
If I have a pinned workflow, if the workflow status changes as a result of a refresh update, then the tree view should update to reflect that same status.

![image](https://user-images.githubusercontent.com/15258962/130327862-92d4d09f-5e83-4a4e-be5d-e03e5a13eff4.png)
![image](https://user-images.githubusercontent.com/15258962/130327866-50d56ac5-7001-4738-8ae9-355147b236b3.png)

For a quick implementation, once you reach this step, 

https://github.com/cschleiden/vscode-github-actions/blob/6c3f8268d5dbafcd4c4ab3bebc41f4091e127b9f/src/pinnedWorkflows/pinnedWorkflows.ts#L196-L196

Call refresh. 
https://github.com/cschleiden/vscode-github-actions/blob/6c3f8268d5dbafcd4c4ab3bebc41f4091e127b9f/src/treeViews/workflows.ts#L26-L26

It's not optimal but gets things working, ideally you take the result from the pinned workflow refresh and then update the entry directly without needing to make another GH call

**Comment by cschleiden** [comment]
Closing in favor of #154
