### ISSUE TITLE
Support actions references in sub folders

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/vscode-github-actions#117]
![image](https://user-images.githubusercontent.com/2201819/130470788-caba9a93-bd56-455f-9894-fbd73ccee88d.png)

**Comment by kzrnm** [comment]
@cschleiden I create pull request that fix the issue in https://github.com/cschleiden/github-actions-parser/pull/48.
Please review the pull requests.

https://github.com/cschleiden/vscode-github-actions/blob/233b9b55ebd8f22f3764a81bbbd05941d379be64/src/workflow/diagnostics.ts#L3
https://github.com/cschleiden/vscode-github-actions/blob/233b9b55ebd8f22f3764a81bbbd05941d379be64/src/workflow/diagnostics.ts#L148-L156

**Comment by cschleiden** [comment]
This should work now.
