### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by Disane87** [cschleiden/vscode-github-actions#12]
Hey, I already used this a few days and now I get an error `bad credentials`. I already regenerated the PAT and stored it again, but nothing works. Any advices here?

![image](https://user-images.githubusercontent.com/956158/78526876-acde1480-77db-11ea-94ba-7dcb87c6d40e.png)

I use your extension within a code-server (https://github.com/cdr/code-server) which works perfectly until today.

**Comment by williamdes** [comment]
I had the same issue and I granted more scopes:
![image](https://user-images.githubusercontent.com/7784660/79201780-dda3f680-7e38-11ea-856a-0e0270e622f3.png)

**Comment by cschleiden** [comment]
@Disane87 could you try again with a token with the `repo` and `workflow` scope? I also made some changes in `0.4.0` to better work with remote editors like code-server.

**Comment by Disane87** [comment]
It seems that this is working 🙃

**Comment by cschleiden** [comment]
Great, closing this then.

**Comment by Demon-DK** [comment]
I suggest to reopen this cause login doesn't worked at all

#### I'm using next setting and approach as shown below
-----------
![image](https://user-images.githubusercontent.com/25489257/81607718-cd524d80-93dd-11ea-90ed-cae41abd957b.png)

Token scope (_for testing have been trying even to give for the token full admin credentials_)
![image](https://user-images.githubusercontent.com/25489257/81607739-d6431f00-93dd-11ea-9587-ac1121c17617.png)
------------
And vscode is yelling 
![image](https://user-images.githubusercontent.com/25489257/81608054-549fc100-93de-11ea-9349-e5fdd049e27c.png)

**Comment by cschleiden** [comment]
> @cschleiden 
> 
> Hello, I suggest to reopen this cause login doesn't work at all
> 
> 
> 
> #### I'm using next setting and approach as shown below
> 
> -----------
> 
> ![image](https://user-images.githubusercontent.com/25489257/81607718-cd524d80-93dd-11ea-90ed-cae41abd957b.png)
> 
> 
> 
> Token scope (_for testing have been trying even to give for the token full admin credentials_)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/25489257/81607739-d6431f00-93dd-11ea-9587-ac1121c17617.png)
> 
> ------------
> 
> And vscode is yelling 
> 
> ![image](https://user-images.githubusercontent.com/25489257/81608054-549fc100-93de-11ea-9349-e5fdd049e27c.png)
> 
> 

You just need to include the token, not the url. That is read from the `origin` remote.

**Comment by Demon-DK** [comment]
@cschleiden 
![image](https://user-images.githubusercontent.com/25489257/81612007-c0852800-93e4-11ea-8dd2-fd0baa33fa4d.png)

Without success - bad credentials

**Comment by Demon-DK** [comment]
@cschleiden 
Really unusual but seems its been Github issue.
I've the notification about after two hours after token creation and therefore its start to work

Can close it again now, thanks )

**Comment by cschleiden** [comment]
@Demon-DK Glad that it works now.
