### ISSUE TITLE
Support remotes that aren't named `origin`

### ISSUE THREAD

**Issue by ddnexus** [cschleiden/vscode-github-actions#126]
Installed in a devcontainer, no errors in the logs, just the qactivation mesage at startup. I also tried to add settings manually, clicking in the refresh button in the panel. No actrivity in the log. No signs that it works, not with the file, not in the panel. 

Did I miss some requirement?

**Comment by kubenstein** [comment]
Im having the same issue... in my case the problem is my github git remote is not under `origin` name.
It seems currently `origin` name is hardcoded and only this name will be recognised:
https://github.com/cschleiden/vscode-github-actions/blob/master/src/git/repository.ts#L58-L62

**Comment by ddnexus** [comment]
Right! Mine too!
