### ISSUE TITLE
Only show parent node when there is more than one

### ISSUE THREAD

**Issue by misolori** [cschleiden/vscode-github-actions#128]
<img width="367" alt="CleanShot 2021-10-27 at 14 18 35@2x" src="https://user-images.githubusercontent.com/35271042/139148711-bcd69322-3221-4342-b47b-f75e8f6d4d31.png">

Currently when there is only one parent node (repo name) there is top-level folder with the name that is repeated and feels like it's a waste of space. Would be better if this only showed up if I had more than one folder. I have this nested into my other GitHub views to consolidate the GitHub views:

<img width="389" alt="CleanShot 2021-10-27 at 14 19 40@2x" src="https://user-images.githubusercontent.com/35271042/139148839-4c4bce34-ab79-48b2-b536-dd352e18a20b.png">

**Comment by cschleiden** [comment]
This is fixed in the latest version.
