### ISSUE TITLE
Reusing workflow not supported

### ISSUE THREAD

**Issue by mattcanty** [cschleiden/vscode-github-actions#129]
GitHub Actions allows reuse: https://docs.github.com/en/actions/learn-github-actions/reusing-workflows

Properties are not recognised by the extension.

![image](https://user-images.githubusercontent.com/2089581/140366203-dc8ef24d-f131-4a76-a238-bd6dcb40c1cf.png)

**Comment by cschleiden** [comment]
Closing in favor of #148
