### ISSUE TITLE
Option for triggering workflow not showing up

### ISSUE THREAD

**Issue by paulhutchings** [cschleiden/vscode-github-actions#13]
The option to trigger the workflow manually using the `repository_dispatch` event is not showing up as an option for me when right-clicking on a workflow, despite including `repository_dispatch` as a trigger event:
![image](https://user-images.githubusercontent.com/36493057/78579977-bbd6be00-77ff-11ea-906e-10c01a41b7d3.png)
![image](https://user-images.githubusercontent.com/36493057/78580305-37386f80-7800-11ea-82b7-5c8402db5f6e.png)

I've added the event as a trigger, pushed the change to GitHub, and refreshed the extension window. 

Any help would be much appreciated, I'm currently using the watch event as a workaround for manually invoking for testing and would much prefer this approach.

**Comment by cschleiden** [comment]
That is a bug, thanks for reporting! I'll try to get a fix out in a bit

**Comment by paulhutchings** [comment]
@cschleiden Thank you for replying so quickly! Much appreciated.

**Comment by cschleiden** [comment]
@paulhutchings This is fixed in v0.1.16. Additionally, if you use `types` to filter `repository_dispatch` it will now pre-populate the input box:

![image](https://user-images.githubusercontent.com/2201819/78848802-ab713f80-79c7-11ea-81aa-c2335d204c5e.png)

**Comment by paulhutchings** [comment]
@cschleiden Awesome! Thank you for the support, this is a great extension!
