### ISSUE TITLE
Unicode characters in logs not displaying correctly

### ISSUE THREAD

**Issue by theogf** [cschleiden/vscode-github-actions#131]
When looking at log outputs with unicode/emoji characters, they always appear as `esc[{a number}m` (see screenshot below).
Unicode is widely used in Julia, so it completely ruins the logs outputs.
![image](https://user-images.githubusercontent.com/11480067/142888754-ec66359b-f54f-4d66-b8fb-87084629e9ec.png)

**Comment by cschleiden** [comment]
This should be fixed now.
