### ISSUE TITLE
Linter doesn't work for composite action .yml files

### ISSUE THREAD

**Issue by purplehat7** [cschleiden/vscode-github-actions#133]
e.g. using [the example Composite Action from the Github docs](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action):

<img width="534" alt="Screen Shot 2022-01-10 at 2 27 42 PM" src="https://user-images.githubusercontent.com/4723669/148848958-c523a668-4be2-49a3-b750-6a89b1e0a705.png">

**Comment by cschleiden** [comment]
This currently only supports workflows, not actions in any form.

**Comment by cschleiden** [comment]
I'm closing this for now as not planned. Might be a good addition for the future, but I won't get to it anytime soon.
