### ISSUE TITLE
Cannot view logs of action run

### ISSUE THREAD

**Issue by haikyuu** [cschleiden/vscode-github-actions#134]
Here is the error I get. Note that I can see the workflow runs
`Command 'GitHub Actions: View logs' resulted in an error (Cannot read property 'gitHubRepoContext' of undefined)`

**Comment by haikyuu** [comment]
This only happens for currently running jobs. Feel free to close this if it's not possible to implement or is not in the roadmap

**Comment by cschleiden** [comment]
This is a limitation of the API unfortunately, we only allow you to download logs once a run is completed.
