### ISSUE TITLE
custom runner labels

### ISSUE THREAD

**Issue by alisalemmi** [cschleiden/vscode-github-actions#138]
thank you for your great extension.
self hosted runner can have custom labels such as x86, linux, dev, arm , ... .

![image](https://user-images.githubusercontent.com/45937252/152301801-df4dcedf-b01e-4871-94f6-5518ba50d89b.png)

**Comment by cschleiden** [comment]
If you have the right permissions for the repository, the extension does pull down the custom labels and also validates them:
![CleanShot 2022-02-03 at 10 53 27](https://user-images.githubusercontent.com/2201819/152409664-dd449e26-297a-45a2-9d6a-dfbbf18265cf.png)

Currently this only works for repo level runners though, not for runners shared by the org or the enterprise.

**Comment by krisrecur** [comment]
Thank you for this amazing extension! Is there anyway to disable this one check so the custom runner labels don't cause a false positive?

**Comment by cschleiden** [comment]
I think moving this from an error to a warning might be appropriate until we can get better APIs in place.

**Comment by cschleiden** [comment]
This should be fixed now.
