### ISSUE TITLE
workflow_dispatch inputs

### ISSUE THREAD

**Issue by ybulakhau** [cschleiden/vscode-github-actions#141]
Hi, can you tell me if there is support for `workflow_dispatch` inputs? Since I'm getting an error now.

`Key 'type' is not allowed`

![image](https://user-images.githubusercontent.com/32245389/153591959-decd6750-f464-456f-89a0-438dc9f872f5.png)

**Comment by dizys** [comment]
Encountered the same problem. Seems to be a miss for  [github-actions-parser](https://github.com/cschleiden/github-actions-parser) which this extension depends on.
Working on a fix [here](https://github.com/cschleiden/github-actions-parser/pull/34).

**Comment by melMass** [comment]
@cschleiden Not sure what the issue is but the PR referenced by @dizys is merged since 👀

**Comment by cschleiden** [comment]
Fixed in 0.23.0
