### ISSUE TITLE
Shell syntax highlighting inside `run:`

### ISSUE THREAD

**Issue by neongreen** [cschleiden/vscode-github-actions#144]
Currently long scripts in `run:` clauses are highlighted as strings.

Would be lovely if they were highlighted as shell scripts instead, the same way e.g. the insides of `<script></script>` tags in HTML files are highlighted as JS.

**Comment by cschleiden** [comment]
This might be possible with an embedded grammar, but there are some questions around different shells etc. I'm closing this for now as not planned, but we might revisit this in the future.
