### ISSUE TITLE
`permissions` does not have all available scopes

### ISSUE THREAD

**Issue by anurag-roy** [cschleiden/vscode-github-actions#147]
[Permissions according to the GitHub Actions Docs](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview)

Getting this error using `id-token` under `permissions`:

![image](https://user-images.githubusercontent.com/53750093/161383424-837c00ee-750d-4306-a44c-ee995896860f.png)

**Comment by cschleiden** [comment]
Fixed in 0.23.0
