### ISSUE TITLE
'workflow_call' is not recognized

### ISSUE THREAD

**Issue by longrunningprocess** [cschleiden/vscode-github-actions#148]
![image](https://user-images.githubusercontent.com/4412848/161765680-d64a0e59-8687-4b87-9d92-e1cd63c1f5c8.png)

I presume as a result of not recognizing `workflow_call` it's also marking inputs as invalid expressions and `secrets` as unknown contexts:
![image](https://user-images.githubusercontent.com/4412848/161766081-5186c3ae-0115-4a77-ac50-5880482b9d92.png)

![image](https://user-images.githubusercontent.com/4412848/161765992-c3ffac5f-009c-438e-a49a-03af84f4e6f4.png)

![image](https://user-images.githubusercontent.com/4412848/161766183-64bc6d8c-f7eb-4845-94a0-1d2ba747e3f5.png)

**Comment by cschleiden** [comment]
Fixed in 0.23.0
