### ISSUE TITLE
Feature request: Integrate Actionlint

### ISSUE THREAD

**Issue by selfagency** [cschleiden/vscode-github-actions#149]
[Actionlint](https://github.com/rhysd/actionlint) is a static checker for GitHub Actions workflows and it currently has no VS Code extension. It would make an excellent addition to yours.

**Comment by laughedelic** [comment]
It looks like there is an extension now: https://marketplace.visualstudio.com/items?itemName=arahata.linter-actionlint

**Comment by selfagency** [comment]
@laughedelic Yes, but it depends on the Linter extension which I have found to be slow and buggy.

**Comment by cschleiden** [comment]
I don't think we can integrate actionlint in the short-term. It has a lot of great features and I hope we can support some of them in the future, but closing this for now.
