### ISSUE TITLE
Show pinned workflow state for current branch

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/vscode-github-actions#15]
Think about if we want to scope the status displayed for pinned workflows, for example, to the currently checked out branch.

**Comment by tstibbs** [comment]
I definitely want this. Having a status bar icon that shows the state of a different branch is really not that helpful. What I want to see is always "did the thing I just pushed break the build". For the same reason, it would make sense for the polling to only run for a period after the push, and then stop polling once its got a result - as there's no point polling github every 30s when you already know the state of build for the last commit.
