### ISSUE TITLE
Unknown content access: github.event.workflow_run.conclusion

### ISSUE THREAD

**Issue by Shrooblord** [cschleiden/vscode-github-actions#152]
Hi there,

I'm getting the error:
```
Unknown context access: 'github.event.workflow_run.conclusion'
```
on the following conditional:
```
if: ${{ github.event.workflow_run.conclusion == 'failure' }}
```
which I took directly from [the GitHub docs here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow).

![Screenshot 2022-04-22 at 12 21 57](https://user-images.githubusercontent.com/3255068/164689763-2c3babb2-612c-40be-b46e-b3ce1ed6e150.png)

This seems like a bug. Can I suppress this error and/or teach `vscode-github-actions` how to recognise this key?

**Comment by Shrooblord** [comment]
Is this something I can rectify in my project or do you need to handle this in the extension code?

**Comment by barryhagan** [comment]
PR for the fix in the parser: https://github.com/cschleiden/github-actions-parser/pull/42

Once that is merged and released, the `github-actions-parser` dependency can be bumped in this project to get the fix.
