### ISSUE TITLE
Bug with `github.ref_type`

### ISSUE THREAD

**Issue by KKimj** [cschleiden/vscode-github-actions#159]
Hello, There is a bug with `github.ref_type`.
Please see below.

Have a good day!
Thanks.

https://docs.github.com/en/actions/learn-github-actions/contexts#example-contents-of-the-github-context

<img width="630" alt="image" src="https://user-images.githubusercontent.com/40026920/170521625-440e0280-38df-4d58-b291-003e417e810c.png">

<img width="808" alt="image" src="https://user-images.githubusercontent.com/40026920/170522119-42f4eaa9-5d52-4e1e-92bc-4f7636ae99c2.png">

**Comment by cschleiden** [comment]
This should be fixed now.

**Comment by KKimj** [comment]
thanks
