### ISSUE TITLE
Why autocompletion doesn't work ?

### ISSUE THREAD

**Issue by chrisleves** [cschleiden/vscode-github-actions#161]
I open any yaml under .github/workflows and there's not completion at all

Is it because I already have a yaml plugin called YAML Language Support by Red Hat, ?

thanks

**Comment by AndriSig** [comment]
It works when I turn that extension of, so I'm assuming they aren't playing nice together.

**Comment by cschleiden** [comment]
I _think_ both extensions should be able to contribute auto-complete options. Do you see any output in the `GitHub Actions` Output window?

**Comment by jornpe** [comment]
Just adding to this as I also have issues getting the autocompletion to work. 

I've installed the extension, and is inside the yml file located under .github/workflows. And in the log you are mentioning I get this:

````log
Activating GitHub Actions extension...
...initialized
Found git extension
Find `origin` remote for repository /d:/Repos/Private/HomeProject
Found git extension
Find `origin` remote for repository /d:/Repos/Private/HomeProject
Found protocol infos 1
Getting infos for repository https://github.com/jornpe/HomeProject.git
Found protocol infos 1
Getting infos for repository https://github.com/jornpe/HomeProject.git
````

So seem like the extension should have been working. 

I had the Azure pipeline extension, but I disabled that. No other yaml extension is installed. This is the yaml settings (not sure if it helps).

````Json
"[yaml]": {
    
    
        "editor.insertSpaces": true,
        "editor.tabSize": 2,
        "editor.autoIndent": "advanced"
    },
````

**Comment by nikitalita** [comment]
Autocompletion works by typing "." after a member, but doesn't in any other context:
![image](https://user-images.githubusercontent.com/69168929/195697491-2c33898f-109e-424c-adfe-0b0f24152b65.png)

The why is probably here: https://github.com/cschleiden/vscode-github-actions/blob/main/src/workflow/diagnostics.ts#L13

Tested this using a standalone version of vscode and only the github actions extension installed. With the YAML extension also installed, it's a bit better, but it's only after either ":" or "." is typed.

**Comment by cschleiden** [comment]
We have made some improvements, please try again and if you're still seeing errors open an issue in https://github.com/github/vscode-github-actions/issues
