### ISSUE TITLE
Support workspaces and complex folder structures

### ISSUE THREAD

**Issue by williamdes** [cschleiden/vscode-github-actions#17]
None of my workflows are detected for now :crying_cat_face: 
![image](https://user-images.githubusercontent.com/7784660/79201952-2196fb80-7e39-11ea-9a92-6bbc3540047f.png)

**Comment by cschleiden** [comment]
Yes you’re right, haven’t really rested that scenario yet. Not quite sure what to do, the GitHub API is per repo of course, so the workflow view would have to support many roots, or multiple sections... 🤔

**Comment by williamdes** [comment]
And how do you detect the project slug ?

**Comment by cschleiden** [comment]
If the currently opened folder is a git repository I'm checking if the `origin` remote points to `github.com` and then take the slug from there. Not perfect, but works in most cases.

**Comment by williamdes** [comment]
Okay, then I guess you could find all the repositories and make a tree of actions

**Comment by williamdes** [comment]
🏓

**Comment by pinalbhatt** [comment]
Do we have any updates here? I still see this issue.

**Comment by cathex-matt** [comment]
🏊🏼‍♂️
