### ISSUE TITLE
Input type of `choice` is not parsing as a valid option despite GitHub documentation.

### ISSUE THREAD

**Issue by glloyd2010f** [cschleiden/vscode-github-actions#174]
On 11/10/2021 it was announced that choice was a supported option for workflow_dispatch inputs, [GitHub Actions: Input types for manual workflows](https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/).

However when I attempt to add a choice input and this extension it says it is invalid, screenshot included
![image](https://user-images.githubusercontent.com/36274646/182613811-bea51059-03f0-4b1c-8a4b-4b768d03dd29.png)

Is this just a schema mismatch between the current github action schema and what the extension is leveraging? Regardless can we get an update to support all the different manual input types.

**Comment by cschleiden** [comment]
This should work now.
