### ISSUE TITLE
When a step `uses` an action, read `outputs` from `action.yml`

### ISSUE THREAD

**Issue by dca123** [cschleiden/vscode-github-actions#175]
I'm setting the environment via 

```
environment:
name: Development
url: ${{ steps.deploy.outputs.url }}
```

My deploy step looks like

```
name: Deploy to Google Cloud
id: deploy
uses: google-github-actions/deploy-cloudrun@v0
```

I get the following error `Unknown context access: 'steps.deploy.outputs.url'`. The deployment works perfectly and the URL is assigned as expected. This is only a linting issue.

Is there any way I could fix this ?

Regards,
Dev

**Comment by cschleiden** [comment]
Thanks for reporting this.

Actions declare their outputs in the `action.yml` file. For `deploy-cloudrun` that would be here:
https://github.com/google-github-actions/deploy-cloudrun/blob/main/action.yml#L159-L161 

Today the extension doesn't parse that part of `action.yml` for referenced actions and therefore doesn't know the `outputs`.  We should add that.

**Comment by cschleiden** [comment]
Updated the title and resolved another issue as duplicate since here we have more information.

**Comment by cschleiden** [comment]
This is now implemented.

**Comment by twelvelabs** [comment]
@cschleiden can you please point me to where this was fixed? I don't see any recent commits in main.
