### ISSUE TITLE
Trigger workflow not work

### ISSUE THREAD

**Issue by Filaind** [cschleiden/vscode-github-actions#178]
If I click the workflow trigger, nothing happens

![Untitled](https://user-images.githubusercontent.com/27895981/185760037-a26e7949-f15f-4211-b03c-ee6e73194a53.gif)

workflow file

![Снимок экрана 2022-08-20 в 19 45 14](https://user-images.githubusercontent.com/27895981/185759790-14e1163a-b046-4acc-8611-d42478aa60f5.png)

GitHub Actions v0.24.2

**Comment by Filaind** [comment]
After some debug i found error

My workspace contains multiple repos

![Снимок экрана 2022-08-20 в 20 05 31](https://user-images.githubusercontent.com/27895981/185760544-3cbc5ffd-8d80-407d-9b6a-a9dad8416db6.png)



This code use `workspaceUri` for get context.
But my `workspaceUri` not include in `gitHubContext.reposByUri`

![Снимок экрана 2022-08-20 в 20 09 04](https://user-images.githubusercontent.com/27895981/185760724-d3341489-3dcc-4a37-aed4-896f56e2453e.png)


![Снимок экрана 2022-08-20 в 20 08 10](https://user-images.githubusercontent.com/27895981/185760677-7a5292a8-8ac0-4678-8e73-1e36b1e37907.png)

**Comment by nitzan-blink** [comment]
having the same issue. 
same end result - clicking "trigger workflow" does nothing, not sure the problem is the same.
any way to debug this? the extension output doesn't show any warnings..

**Comment by nitzan-blink** [comment]
[cschleiden](https://github.com/cschleiden) can you assist? how can I tell what's going wrong?
