### ISSUE TITLE
Show commit message in the list of workflow runs

### ISSUE THREAD

**Issue by robertrossmann** [cschleiden/vscode-github-actions#18]
When I look at the list of recent workflow runs I am quite clueless which revision was checked by that run. In other words, seeing the run ID and commit hash in the list is not what would help me navigate the list.

Instead, I propose to see the commit message or pull request title, or tag, or basically any other user-friendly text in the list, if available. That would help me navigate the list much better than seeing the run IDs. 🙏 ❤️ 

In ideal world, the list would show the "thing" that triggered the workflow in a way that is user-recognisable based on the trigger. So when you push a commit, it shows the commit message. When you create a tag, it shows the tag name etc. Personally I would be absolutely happy with having this work with commits, pull requests and tags.

Thanks for considering this! Great extension, finally I don't have to leave VS Code to check my workflow status. 💯 

![list of run IDs](https://user-images.githubusercontent.com/3058150/80363209-29688e00-8884-11ea-9e6c-8ee84af401bd.png)

**Comment by robertrossmann** [comment]
I'm still very interested in having the workflow run titles have better descriptions, thank you very much robot 🤖 ! 😇

**Comment by r-darwish** [comment]
@cschleiden the stale bot decided to close this anyway. Could you please reopen?
