### ISSUE TITLE
Permissions grant prompt links to sketchy empty organization

### ISSUE THREAD

**Issue by sparr** [cschleiden/vscode-github-actions#181]
In addition to the extremely broad permissions this extension requests, I also found another part of the permission grant process concerning.

> GitHub for VS Code by [Visual-Studio-Code](https://github.com/Visual-Studio-Code)

> wants to access your sparr account

That link goes to a completely empty organization. It has a name and two links (website and twitter). No repos, no projects, no members. It looks exactly as it would if a malicious actor created an empty org, which they could right now with a name like VisualStudio-Code (which is available).

On top of that, it's also a little strange that the extension from this repo is requesting permissions using a key/cert/whatever for an organization that doesn't own this repo, with a name that doesn't match this extension.

I'd feel a lot better about granting this extension at least some permission (in a future where #167 makes some progress) if this was addressed in some way.

**Comment by cschleiden** [comment]
> On top of that, it's also a little strange that the extension from this repo is requesting permissions using a key/cert/whatever for an organization that doesn't own this repo, with a name that doesn't match this extension.

That is the official VS Code organization used by the VS Code GitHub login flow, it's nothing this extension can control.

> In addition to the extremely broad permissions this extension requests,

Unless you enable organization features, the extension shouldn't request any additional permissions besides what the VS Code GitHub integration requires.

**Comment by sparr** [comment]
>  it's nothing this extension can control.

It's probably not a reasonable approach and not one I'd request or recommend, but this extension could do its own github auth, using its own cert/key. Or, more reasonably and as requested in #167, it could optionally just not talk to github at all.

> the extension shouldn't request any additional permissions besides what the VS Code GitHub integration requires.

I don't know if there's a way for a user to tell that it's the integration requiring the permissions in question.

**Comment by sparr** [comment]
https://github.com/cschleiden/vscode-github-actions/blob/main/src/auth/auth.ts

Code rearranged and clipped for clarity:

```typescript
const DEFAULT_SCOPES = ["repo", "workflow"];
const ORG_SCOPES = [...DEFAULT_SCOPES, "admin:org"];
function getScopes(): string[] {
  if (orgFeaturesEnabled()) {
    return ORG_SCOPES;
  }

  return DEFAULT_SCOPES;
}
export async function getSession(): Promise<vscode.AuthenticationSession> {
  const existingSession = await vscode.authentication.getSession(
    AUTH_PROVIDER_ID,
    getScopes(),
    {
      createIfNone: true,
    }
  );
```

The `repo` scope you're requesting is the one that "Grants full access to public and private repositories including read and write access to code, commit statuses, repository invitations, collaborators, deployment statuses, and repository webhooks. Note: In addition to repository related resources, the repo scope also grants access to manage organization-owned resources including projects, invitations, team memberships and webhooks. This scope also grants the ability to manage projects owned by users."

**Comment by cschleiden** [comment]
> Can you recommend a more appropriate place to file an issue against the integration this extension is using?

The official github authentication extension lives here: https://github.com/microsoft/vscode/tree/b72671133b00473ea3494c01d8dea71965fda5a2/extensions/github-authentication

**Comment by cschleiden** [comment]
Regarding the `repo` scope: yes, it's true that this gives a lot of access. However, there is no alternative if you want to access any repository information at all: https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps 

In an ideal world, there would be a way to get only read access to public repos, or to get only read access to the workflow APIs for public repositories, and only request write access when needed but currently that's not possible.

As mentioned above, the only thing that could be done is to provide _only_ the static YAML editing features without displaying workflows and runs and dynamic auto-completion as suggested in #167
