### ISSUE TITLE
Support `inputs` context

### ISSUE THREAD

**Issue by damusix** [cschleiden/vscode-github-actions#185]
Getting a lint error when using `inputs.ABC` in a workflow

**Declaration**
![Screen Shot 2022-09-23 at 5 38 29 PM](https://user-images.githubusercontent.com/4218587/192060206-2345631e-2c5e-463e-9007-d1dc993aa58a.png)

**Usage**
![Screen Shot 2022-09-23 at 5 36 09 PM](https://user-images.githubusercontent.com/4218587/192060209-d32e6973-da9b-4da2-9b3f-db6418f4db94.png)

**Comment by AdamRaichu** [comment]
Still present in `v0.24.4`.

**Comment by cschleiden** [comment]
This should work now.
