### ISSUE TITLE
Support dynamic names for workflow runs (`run-name`)

### ISSUE THREAD

**Issue by SevereCloud** [cschleiden/vscode-github-actions#189]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/14944123/195034192-273a5b08-e1c3-476f-8336-964853d860b8.png">
<img width="864" alt="image" src="https://user-images.githubusercontent.com/14944123/195034713-f102bee9-7222-433c-a1fd-4f23d86486bd.png">

- [Blog](https://github.blog/changelog/2022-09-26-github-actions-dynamic-names-for-workflow-runs/)
- [Documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#name).

**Comment by cschleiden** [comment]
This is now supported!
