### ISSUE TITLE
Support monorepo

### ISSUE THREAD

**Issue by moalamri** [cschleiden/vscode-github-actions#191]
Hi,
Thank you so much for this extension,
Is it possible to add monorepo support?
I basically have nested projects under the main repository, and opening any of those projects will not resolve actions from parent project/repo
When I open the main project at the root level the extension shows pinned actions, but nested projects will give this error:
```
Error running command github-actions.explorer.refresh: command 'github-actions.explorer.refresh' not found. This is likely caused by the extension that contributes github-actions.explorer.refresh.
```
I tried to add the paths per project as `'../.github/workflows/build.yml'`, but still not resolved and give the same error.

Thank you so much.

**Comment by moalamri** [comment]
The issue is gone if I copy `.github` to all nested workspaces. Is it possible for the git extension API to locate the repo root folder?
If so, then monorepo is possible to be implemented

**Comment by cschleiden** [comment]
We are not planning on improving this currently. We might revisit, but for now we expect a workspace folder to include the `.github/workflows` folder.
