### ISSUE TITLE
Unable to enable auto-completion

### ISSUE THREAD

**Issue by SiegeSailor** [cschleiden/vscode-github-actions#194]
# Overview

Somehow the auto-completion feature doesn't work on my VS Code. There should be a hint like "composite" in the image below (I actually don't see any auto-completion support):

<img width="1496" alt="Screen Shot 2022-10-13 at 12 44 16" src="https://user-images.githubusercontent.com/39463416/195656380-53715bd5-0405-498e-95f5-fa128a246f67.png">

However, I am able to view and dispatch actions from my sidebar:

<img width="1496" alt="Screen Shot 2022-10-13 at 12 44 32" src="https://user-images.githubusercontent.com/39463416/195656516-cbdf0351-814c-4e30-8aa3-c227912afc41.png">

I have tried to uninstall and install this extension many time.

## Detail

The following is my file structure. [Here](https://github.com/BUMETCS673/2022Fall-Team1-StageSourceProject/tree/feature/github-actions) is the repository:

```bash
├── .github/
│   ├── workflows/
│   │   ├── [workflow].yml
│   ├── actions/
│   │   ├── [action]
│   │   │   ├── action.yml
├── document/
├── application/
├── database/
├── server/
├── ...
└── README.md
```

- **GitHub Actions Extension on VS Code**: `v0.24.2`
- **VS Code**: `v1.72.1`

**Comment by cschleiden** [comment]
From the screenshot it looks like you're editing an `actions.yml` file, at the moment auto-complete supports only workflows in the `.github/workflows` folder.
