### ISSUE TITLE
Annoying authentication modal on startup

### ISSUE THREAD

**Issue by zardoy** [cschleiden/vscode-github-actions#196]
For some reason, sometimes GitHub authentication provider forgets me.

Whenever it happens, all extensions want me to sign in here:

<img width="300" alt="Screenshot 2022-10-19 at 01 14 08" src="https://user-images.githubusercontent.com/46503702/196555256-b5cb4d1a-1b6b-4dcc-9e3a-4268301be4d3.png">

And this is the only extension that shows me modal (from what I have).

TL;DR, please remove `createIfNone: true` from here:
https://github.com/cschleiden/vscode-github-actions/blob/a1fd4aa2ea193a5df693959486320aeafaa2b7d8/src/auth/auth.ts#L25-L31 which is being called on extension activation

From vscode docs:

```typescript
/**
* If true, a modal dialog will be shown asking the user to sign in. If false, a numbered badge will be shown
* on the accounts activity bar icon. An entry for the extension will be added under the menu to sign in. This
* allows quietly prompting the user to sign in.
*
* If there is a matching session but the extension has not been granted access to it, setting this to true
* will also result in an immediate modal dialog, and false will add a numbered badge to the accounts icon.
*
* Defaults to false.
*/
```

So its ok to request this one on some action actually requiring authentication, but not workflow editing for example.

I also wonder why this extension gets activated by file detection? Why this extension doesn't use these activation events?: onLanguage:yaml, onView, onCommand

**Comment by cschleiden** [comment]
That makes sense, we'll take a look at the popup. Thanks for reporting and providing context!

**Comment by zardoy** [comment]
Was it fixed in extension?
