### ISSUE TITLE
Autocomplete doesn't work on VSCode 1.68.1

### ISSUE THREAD

**Issue by diegotecbr** [cschleiden/vscode-github-actions#201]
The autocomplete functionality just doesn't work in VsCode 1.68.1, I've reinstalled the extension several times.
![info](https://user-images.githubusercontent.com/104787607/199798447-b7df9f1c-7088-47c2-9394-4bc9d3a20386.PNG)

**Comment by roi-zentner** [comment]
+1 Never worked for me. I'm now running VS Code 1.73.1

**Comment by zhaoqiu-china** [comment]
+1 Me too. I'm now running VS Code 1.73.1

**Comment by Jacob-Sonne** [comment]
+1 doesn't work for me either. VS Code 1.75.0

**Comment by cschleiden** [comment]
Please try again now and open a new issue in https://github.com/github/vscode-github-actions/issues if this is still happening.
