### ISSUE TITLE
Dynamic matrix.include triggers errors

### ISSUE THREAD

**Issue by sargunv** [cschleiden/vscode-github-actions#204]
<img width="580" alt="CleanShot 2022-11-13 at 12 45 14@2x" src="https://user-images.githubusercontent.com/1320357/201543776-a8a73431-4a58-410c-b37e-df9b1876d873.png">

See the workflow here: https://github.com/sargunv/node-sandbox/blob/dc39d7a0a81d57edf1a8cf118782535631c024b8/.github/workflows/release.yml#L40

Errors are: "Expected sequence, found value" on the `matrix.include`, and "Unknown context access" below at the usage points.

**Comment by cschleiden** [comment]
This should be fixed now.
