### ISSUE TITLE
Disable Extention Linting all together

### ISSUE THREAD

**Issue by Sharpz7** [cschleiden/vscode-github-actions#207]
Hi, I just want to use this extention for its intergration with github.com, not linting my files. Is there a way to disable this?

Thanks.

**Comment by cschleiden** [comment]
That's currently not possible. Is there a specific reason? Are you running into issues?

**Comment by Sharpz7** [comment]
Yeah - I kind of ran into so many I just gave up using the extention, apoligies. For reference, these are the actions I was using: https://github.com/G-Research/armada/tree/master/.github/workflows

**Comment by cschleiden** [comment]
No worries, we are currently working on an improved version of the extension and will make sure to test against the workflows you've shared (thanks for that 🙇)!

**Comment by Sharpz7** [comment]
Great! I'd love to know when that's released so I can give this a go again :))
