### ISSUE TITLE
Conditional statements do not evaluate correctly

### ISSUE THREAD

**Issue by Pwuts** [cschleiden/vscode-github-actions#210]
```YAML
# link to a deployment environment for deploy tracking
environment: ${{ github.ref_name == 'master' && 'production' || 'development' }}
```
This line (defining `jobs.build.environment` in my workflow) gives me a linting error `'NaN' is not in the list of allowed values`, while the expression is equivalent to `github.ref_name == 'master' ? 'production' : 'development'`, which always evaluates to a string.

**Comment by cschleiden** [comment]
This should be fixed now.
