### ISSUE TITLE
Key `run-name` is not allowed

### ISSUE THREAD

**Issue by devLucasOAK** [cschleiden/vscode-github-actions#216]
Just started today using the [Quickstart Doc](https://docs.github.com/pt/actions/quickstart), and it is throwing this:
![image](https://user-images.githubusercontent.com/29466593/216798288-b3c05fbf-6eda-4b51-9a94-29e3fa01f50b.png)

I think the extension is outdated cause this key is kinda new ([CHANGELOG](https://github.blog/changelog/2022-09-26-github-actions-dynamic-names-for-workflow-runs/)).

**Comment by cschleiden** [comment]
This should work now.
