### ISSUE TITLE
Support job summaries

### ISSUE THREAD

**Issue by PavanMudigondaTR** [cschleiden/vscode-github-actions#219]
Hi, 

I am really thankful for this awesome tool.

I was wondering if it’s possible to see GitHub Build/Job Summaries in VS Code GitHub Action extension instead of going to browser again for this missing information. 

<img width="946" alt="image" src="https://user-images.githubusercontent.com/86745613/223574032-0fd1f437-081f-4c02-80f3-ba22c16d2281.png">

**Comment by cschleiden** [comment]
Transferred to https://github.com/github/vscode-github-actions/issues/25
