### ISSUE TITLE
This is driving me nuts. I am able to add one secret and it is working fine. I add another secret, via VSCode and it doesn't showup on GitHub and vice versa.

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/vscode-github-actions#221]
This is driving me nuts. I am able to add one secret and it is working fine. I add another secret, via VSCode and it doesn't showup on GitHub and vice versa.

What am I doing wrong here? They key is just alphabets with underscores 😭

_Originally posted by @siddharth2023 in https://github.com/cschleiden/vscode-github-actions/issues/101#issuecomment-1470679525_

**Comment by cschleiden** [comment]
Please try again with the new version and if you're still experiencing this issue, report in https://github.com/github/vscode-github-actions/issues 🙇

**Comment by siddharth2023** [comment]
Working like magic!!!!

Thank you so much :) You can close this issue.
