### ISSUE TITLE
Doesn't work for fork with upstream

### ISSUE THREAD

**Issue by rikoe** [cschleiden/vscode-github-actions#23]
If my fork is my origin, and the GitHub actions are in the upstream remote (which I believe is a fairly standard setup with git), the upstream actions aren't picked up.

To get it to work, I have to check out the upstream repo as "origin", and name the remote for my fork something else, e.g. with my user name.

This means it is less useful for my team, most of which use the origin-upstream convention.

**Comment by rikoe** [comment]
Here is a link to the GitHub documentation instruction users to set up their remotes in this way: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork

**Comment by cschleiden** [comment]
Yes, that is a known limitation. Not sure yet what might be the best way to solve this. Maybe check for `upstream` first and have that take precedence over `origin`.

Another approach could be to check all remotes for something `github.com` hosted and show workflows for all remotes. Something similar would also be required for workspaces (https://github.com/cschleiden/vscode-github-actions/issues/17).

**Comment by xleliberty** [comment]
Hi, 
thanks for this awesome extension!
I would say that a config key to choose the needed remote would be enough. 

Regards

**Comment by nschonni** [comment]
Maybe the "Configure Remotes" approach of https://github.com/Microsoft/vscode-pull-request-github would be applicable here

**Comment by cschleiden** [comment]
I like the idea of adding a workspace-level settings key to pick a non-default remote!
