### ISSUE TITLE
PAT scope read-only

### ISSUE THREAD

**Issue by inwardmovement** [cschleiden/vscode-github-actions#25]
Hi,

Thanks for your very good extension.
For security reasons I tried to login with a default/read-only scope PAT and it seems to work (I just won't be able to trigger workflow runs). You may want to specify that you can work with a read-only PAT in the readme, and even make it the default option, why not.

Have a good day!

**Comment by cschleiden** [comment]
The extension doesn't use PATs anymore, instead it uses the GitHub authentication built into VS Code.
