### ISSUE TITLE
Empty workflows

### ISSUE THREAD

**Issue by acidos** [cschleiden/vscode-github-actions#26]
Hello,

I am trying to understand why my "Workflows" pane is empty.
I've generated PAT, assigned repo and workflow. I have opened project, containing .github folder, which in turn has number of functioning .yml files.

What else I should do to see something in "Workflows" pane?

**Comment by cschleiden** [comment]
Does your local clone of your repository has an `origin` remote that points to `github.com`?

**Comment by acidos** [comment]
I believe so

```
$ git remote -v
origin  git@github.com:acidos/test.git (fetch)
origin  git@github.com:acidos/test.git (push)
```

**Comment by adrian920110** [comment]
https://github.com/cschleiden/vscode-github-actions/issues/43#issuecomment-692538980
