### ISSUE TITLE
Update icon

### ISSUE THREAD

**Issue by inwardmovement** [cschleiden/vscode-github-actions#27]
How can I make use of [this icon](https://github.com/cschleiden/vscode-github-actions/blob/master/resources/icons/dark/conclusions/success.svg) instead of having the following?
![image](https://user-images.githubusercontent.com/9438102/84368984-8753f980-abd6-11ea-9f02-0a7b74ea1eec.png)

[New pass icon](https://code.visualstudio.com/updates/v1_46#_new-codicon-icons)

**Comment by cschleiden** [comment]
That's not possible unfortunately. As far as I know, VS Code does not support custom icons in the status bar, it **has** to be one from the VS Code icon set: https://github.com/microsoft/vscode-icons

**Comment by inwardmovement** [comment]
You cannot use the [new "pass" Codicon](https://code.visualstudio.com/updates/v1_46#_new-codicon-icons) yet?

**Comment by cschleiden** [comment]
Oh wow, when did that happen? Then yes, of course :)

**Comment by inwardmovement** [comment]
Cool! They just released that in the May update.

**Comment by inwardmovement** [comment]
There is now a new [pass-filled](https://code.visualstudio.com/updates/v1_52#_updated-codicons) icon, maybe you would want to use it instead.
