### ISSUE TITLE
Workflow Refresh Interval doesn't affect Action Bar

### ISSUE THREAD

**Issue by JustinGrote** [cschleiden/vscode-github-actions#33]
Love this extension, has saved me so much time.

When setting a faster refresh time for a file, it works in the status bar:
![image](https://user-images.githubusercontent.com/15258962/85312119-3ca26f00-b46b-11ea-812b-daa9a9f93956.png)

However the Action Bar view doesn't refresh at the same interval. At all actually, so the same refresh trigger should occur on this pane as well:
![image](https://user-images.githubusercontent.com/15258962/85312194-5479f300-b46b-11ea-93d9-d01f8c5f4785.png)

**Comment by cschleiden** [comment]
> Love this extension, has saved me so much time.

Thanks! 

For the refresh: yes, the view doesn't yet refresh at all unless you manually hit the refresh button.

**Comment by JustinGrote** [comment]
@cschleiden Should I submit this separately as a feature enhancement request?
