### ISSUE TITLE
Allow for Github Integrated Login rather than PAT

### ISSUE THREAD

**Issue by JustinGrote** [cschleiden/vscode-github-actions#34]
Issue Type: <b>Feature Request</b>

VSCode now supports extensions being able to use the saved Github Credentials in code
![image](https://user-images.githubusercontent.com/15258962/85960619-bea60280-b959-11ea-82ec-df4f7ffdae7f.png)

Consider using this process rather than the PAT process (or fallback to PAT if this doesn't work)

Extension version: 0.6.0
VS Code version: Code - Insiders 1.47.0-insider (9bf6af04dcb5c2e531cedca83cd188939ca1b0db, 2020-06-26T18:55:07.038Z)
OS version: Windows_NT x64 10.0.19041

**Comment by cschleiden** [comment]
Yes, the code is ready, I just have to wait for it to move into the stable release. It’s currently in the June iteration.. so 🤞 

Tracked in: https://github.com/cschleiden/vscode-github-actions/issues/20
