### ISSUE TITLE
After inserting a wrong PAT once, the extension does not work even with a correct PAT

### ISSUE THREAD

**Issue by renanborgez** [cschleiden/vscode-github-actions#35]
@cschleiden Sorry by the title, it does work indeed, however it was a bit tricky for me to discover that.

I installed the extension by the first time and I inserted a wrongly created PAT (with less permissions than necessary). 
After trying using the extension (with the wrong PAT) I correctly received the `An error has occurred` message.

Reading the docs I realised that I should have added more permission. So I deleted my old PAT, created a new one with the right permissions and I inserted it in the extension by using the following menu:
![image](https://user-images.githubusercontent.com/1863024/86000819-56652880-ba0e-11ea-924b-04d56e0a9ba7.png)

After inserting the CORRECT PAT I've just received the following message:
![image](https://user-images.githubusercontent.com/1863024/86001097-b4920b80-ba0e-11ea-9d5d-5c2e1d532c27.png)

I tried many times with the `repo` and `workflow` permissions enabled but the problem kept happening.
So I decided to try to uninstall and install it again. (also reloading the VSCode)

Even before inserting the PAT again, the extension started to work properly!!!!!!!

After trying many times this flow, I realised that is necessary to **ALWAYS** reload VSCode if you want to change the PAT.

**Summarising**:

Insert a wrong PAT, extension does not work, fix the PAT and insert it again, extension (still)does not work, reload VSCode, extension does work (without any changes).

**Comment by cschleiden** [comment]
Thanks for the detailed description and the repro steps!

The new vscode authentication API seems to be finally moving into the stable release, once that's done #20 should simplify all of this by a lot.

**Comment by FonsRademakers** [comment]
Same problem here. Regenerated PAT but where do I insert it?

**Comment by FonsRademakers** [comment]
Ok found it and restart of vscode solves it.

**Comment by albertorm95** [comment]
any new about this?

**Comment by doitandbedone** [comment]
Having the same issue, even restarting does nothing, can the known workaround please be posted for the time being?

Thanks!

**Comment by cschleiden** [comment]
Using the `login` command and then reloading VS Code doesn't work?
What OS are you on?

**Comment by albertorm95** [comment]
@cschleiden MacOS, and no, login didn't work :(

**Comment by renanborgez** [comment]
@cschleiden just to let you know, I'm also using MacOS (Catalina 10.15.5)

**Comment by akapur1784** [comment]
any update on this issue. I am facing the same issue on MacOS.

**Comment by rajyraman** [comment]
I cannot get the auth working either event with correct token.

**Comment by cschleiden** [comment]
When you store a new token, the old one should be overwritten. If now, you could manually delete it from the Keychain on MacOS:

![image](https://user-images.githubusercontent.com/2201819/88853995-7c185580-d1a5-11ea-8f1e-974e42528a09.png)

**Comment by rajyraman** [comment]
@cschleiden - That was it 😄. I had to delete the credentials in Windows, re-enter and re-start code. It works now.

![image](https://user-images.githubusercontent.com/5035266/88861361-23969600-d241-11ea-8ff8-01a6cba1fe3d.png)

**Comment by cschleiden** [comment]
@rajyraman awesome, great to hear! 

I really hope the VS Code team GAs the authentication API soon...

**Comment by akapur1784** [comment]
@cschleiden The solution provided for Mac OS did not work. :(

**Comment by cschleiden** [comment]
> @cschleiden The solution provided for Mac OS did not work. :(

Hm, what do you mean by that? What did you do and what do you experience now?

**Comment by akapur1784** [comment]
@cschleiden 
I deleted the credentials from Keychain, I entered the PAT in the login space again and restarted VS code.
I still get "An error has occurred :(" message

**Comment by akapur1784** [comment]
@cschleiden any update on this bug for Mac OS?

**Comment by cschleiden** [comment]
@akapur1784 I can't repro unfortunately. Could you open the vs code dev tools, do you see more details about the error there? 

Otherwise I'm expecting the VS Code July release to drop any day now: https://github.com/microsoft/vscode/issues/103792

Within a day or so after the release I'll be able to update the extension to not require the manual PAT entry.

**Comment by cschleiden** [comment]
I have just released version 0.7.0 with integrated VS Code authentication support, closing this for now.
