### ISSUE TITLE
Unable to login with PAT

### ISSUE THREAD

**Issue by irongut** [cschleiden/vscode-github-actions#38]
I'm having problems getting the PAT to work. I've created a PAT with `admin:org, repo, workflow` permissions and copied the token. Then clicked login in the extension and pasted the token into the command pallete that appears. Every time I get the error:

`:( An error has occured while retrieving workflows: Token required`

I've deleted the credentials in Windows, restarted VSCode and tried a few times but no joy.

My account has 2FA enabled if that matters. Any idea what I'm doing wrong?

**Comment by AndreyBronin** [comment]
Had the same issue, the plugin works after VS Code reload

**Comment by cschleiden** [comment]
I have just released version 0.7.0 with integrated VS Code authentication support, please give this a shot
