### ISSUE TITLE
Support `workflow_dispatch`

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/vscode-github-actions#39]

**Comment by MichaelCurrin** [comment]
I see this is already configured.

https://github.com/cschleiden/vscode-github-actions/blob/build-13/.github/workflows/build-preview.yml#L4

Does it work as expected?

Perhaps have two triggers in the same config - one for the manual workflow dispatch and one using a scheduled run at say midnight.

**Comment by cschleiden** [comment]
No that works, this is about supporting triggering a workflow using `workflow_dispatch` from the extension. Similar to how `repository_dispatch` is supported today:
![](https://github.com/cschleiden/vscode-github-actions/raw/master/media/rdispatch.gif)

**Comment by MichaelCurrin** [comment]
Ok thanks that makes sense.

**Comment by cschleiden** [comment]
This is now included in v0.10.0.
