### ISSUE TITLE
[Bug] An error has occured : Not found

### ISSUE THREAD

**Issue by ashwin-phadke** [cschleiden/vscode-github-actions#43]
I am constantly getting an error `An error has occured : Not found` even after trying to sign in multiple times and have also installed and reinstalled the extension, but I still am unable to view my actions.

- I can see my actions folder in the file browser.
- Attaching screenshots below for reference.
- I opened the link to access Github using VScode and then it returned to VScode to open the URL, i was able to see a `signing in to Github` notification for like a second and then it went away.

![Screenshot from 2020-09-11 22-01-55](https://user-images.githubusercontent.com/23502062/92950627-a171d200-f47a-11ea-8a3a-02ff7513ce00.png)
![Screenshot from 2020-09-11 22-01-46](https://user-images.githubusercontent.com/23502062/92950635-a33b9580-f47a-11ea-9497-1a62e5565395.png)

**Comment by ashwin-phadke** [comment]
Found #26 having the same issue.

**Comment by adrian920110** [comment]
![Captura de pantalla de 2020-09-15 03-54-07](https://user-images.githubusercontent.com/16693589/93182009-2cff9300-f707-11ea-9ef6-36b177218cb9.png)

It happens when you don't open the root folder. The first, I have several repositories open and I do not charge the Actions of all. In the second I only opened one and immediately loaded the actions

**Comment by ashwin-phadke** [comment]
Yes , it opens/shows the actions only if that particular repository is opened. 
However generally when you `git cone` inside a folder say named `git repositories` or your home folder it doesn't work. 

[Suggestions or feature-request] : 
Are there any plans to make it work regardless of whether you have opened that particular repository or a directory of repositories  as the `.github` folder would still be there for each directory and then if one were to open a different repo one would have to open multiple VSCode windows to check on all actions/code. 
It is also notable that one doesn't work on multiple repositories at the same time but having to open a new window just to switch repositories and then code and watch the workflows seems rather different.

[Reviews] : 
This extension is really helpful and does save a lot of time.

**Comment by adrian920110** [comment]
It really saves a lot of time. But, for example, in a miservices environment like I work, I need to open many repositories at the same time, and it is super easy for me to have everything in a single window. You would have to open multiple environments to do the same.

But if you save a lot of time, except for that I would use it more, that's a shame. but be sure someone reads this and adds it, or ourselves ...

**Comment by cschleiden** [comment]
There is an existing issue for supporting workspaces and in general more complex folder structures: https://github.com/cschleiden/vscode-github-actions/issues/17
but this would require some bigger changes to the UI, I'm not sure how soon that could get done.

**Comment by robert-spring** [comment]
sorry to necro, but any news on this? 
i see the workflow #17 got merged, but i still see the problem.

**Comment by cschleiden** [comment]
@robert-spring do you have more information of your concrete scenario? Are you using a workspace?
