### ISSUE TITLE
No prompt after selecting the "Github actions: Login" command

### ISSUE THREAD

**Issue by helloguille** [cschleiden/vscode-github-actions#50]
When I select "Github actions: Login" from the command palette, nothing happens.

Extension Version: v0.9.0
VS Code: 1.50.1

**Comment by beizhedenglong** [comment]
same!

**Comment by John118118** [comment]
I see this error: `Command 'GitHub Actions: Login' resulted in an error (command 'github-actions.auth.org-login' not found)`

**Comment by cschleiden** [comment]
I have removed the login command in the latest version, login is now handled via the GitHub authentication provider.
