### ISSUE TITLE
Cannot Enable Extension on a per-workspace basis if disabled globally.

### ISSUE THREAD

**Issue by JustinGrote** [cschleiden/vscode-github-actions#51]
Issue Type: <b>Bug</b>

1. Disable Extension
1. Reload
1. Try "Enable Extension (workspace)"
1. Extension will remain greyed out.

Don't see to have an issue with any other extension.

Extension version: 0.9.0
VS Code version: Code - Insiders 1.52.0-insider (ee46c1f89ebb213e0827886f1688c0fbb55be49f, 2020-11-13T05:37:45.836Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (1.15GB free)|
|Process Argv|--crash-reporter-id c46712d6-a98d-4728-ab12-732cb7b0c555|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by cschleiden** [comment]
This is now fixed in master, going to be included in the next version. Thanks for reporting!
