### ISSUE TITLE
Support include/exclude for `matrix`

### ISSUE THREAD

**Issue by vadi2** [cschleiden/vscode-github-actions#54]
My [workflow file](https://github.com/Mudlet/Mudlet/blob/development/.github/workflows/build-mudlet.yml) is throwing up quite a few errors with the extension even though it is parsed and used correctly by Github, what could be wrong?

![Workspace 1_454](https://user-images.githubusercontent.com/110988/99504770-44196600-2980-11eb-8876-fca5cf0d65f0.png)

**Comment by cschleiden** [comment]
That's a bug :) Haven't considered using expressions for `runs-on` even though it's supported.

**Comment by Cyberbeni** [comment]
It works for me but it says `ubuntu-18.04` is not a supported value and autocomplete only offers the `*-latest` tags and `self-hosted`

**Comment by cschleiden** [comment]
> It works for me but it says `ubuntu-18.04` is not a supported value and autocomplete only offers the `*-latest` tags and `self-hosted`

👍  Tracked as https://github.com/cschleiden/vscode-github-actions/issues/62

**Comment by ThiefMaster** [comment]
I guess this is the same bug?

![image](https://user-images.githubusercontent.com/179599/105875468-1eeb4880-5ffe-11eb-8792-701d4178ce33.png)

**Comment by cschleiden** [comment]
@ThiefMaster how do you setup your matrix strategy?

**Comment by ThiefMaster** [comment]
https://github.com/ThiefMaster/indico-plugins/blob/9611d559f1e889145f7779a0ed1818de4f7e9d89/.github/workflows/ci.yml#L185

**Comment by cschleiden** [comment]
@ThiefMaster ah yes, that's the same bug then!

**Comment by cschleiden** [comment]
Fixed in 0.15.0
