### ISSUE TITLE
Support valid GitHub Actions expression syntax

### ISSUE THREAD

**Issue by Xunnamius** [cschleiden/vscode-github-actions#55]
![badbadbad](https://user-images.githubusercontent.com/656017/99910327-eacc7200-2cb2-11eb-9e92-d82b5b45a71d.png)

Related to #54. Currently, the valid syntax in [this example](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#fromjson) is not supported. Also, it doesn't seem like evaluations of environment variables are done in the same way GitHub Actions does them, which causes a bunch of errors in my [valid perfectly functional workflow file](https://github.com/Xunnamius/workflow-playground/blob/main/.github/workflows/build-test-deploy.yml).

That is: it's my general purpose package publish/software release workflow and it works perfectly fine in GitHub Actions, so I expect vscode-github-actions doesn't generate errors. Otherwise, love this extension, great work! 🎉🎉

**Comment by cschleiden** [comment]
Closing and tracking in #64
