### ISSUE TITLE
Support for GH Enterprise

### ISSUE THREAD

**Issue by bguedel** [cschleiden/vscode-github-actions#58]
Does this currently support or have planned future support for github enterprise?

I see step 2 in the readme specifically says github.com.

**Comment by cschleiden** [comment]
No ETA yet, but want to tackle this eventually for the release of GHES 3.0

**Comment by bguedel** [comment]
Commenting so its not stale

**Comment by joshbouganim** [comment]
any ETA on this? is it more complicated than exposing an editable hostURL setting?

**Comment by florian30491** [comment]
Would also be interested in a support for GHES.

**Comment by bguedel** [comment]
does this mean the issue has been resolved?
