### ISSUE TITLE
Workflow schema update for job environments

### ISSUE THREAD

**Issue by benc-uk** [cschleiden/vscode-github-actions#63]
Jobs now support an `environment` field
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idenvironment

The extension isn't aware of this and soon as you use it, you get a lot of red squiggly lines of doom!
![image](https://user-images.githubusercontent.com/14982936/104033915-186c6c80-51c8-11eb-88a1-512fbd2d5cd8.png)

The current schema is here
https://json.schemastore.org/github-workflow

**Comment by cschleiden** [comment]
Updated in v0.11.0.
