### ISSUE TITLE
Could not get token from the GitHub provider.  Please sign-in and allow access.

### ISSUE THREAD

**Issue by iansinnott** [cschleiden/vscode-github-actions#66]
Hello, I'm getting this error message. I assume it's just something to do with my overall configuration, but it's unclear. How is this supposed to work?

Error message:

```
Could not get token from the GitHub provider. 
Please sign-in and allow access.
```

I get this when clicking the refresh button. 
![2021-01-30 at 11 17 AM](https://user-images.githubusercontent.com/3154865/106345658-c8775600-62ec-11eb-8861-8256a408162c.png)

Edit: typo

**Comment by cschleiden** [comment]
You need sign into VS Code using your GitHub account: 
![image](https://user-images.githubusercontent.com/2201819/106392564-413ae880-63a7-11eb-8b67-d06c1eede4ea.png)

**Comment by pluma** [comment]
Thanks @cschleiden this worked for me. I had to sign out of GitHub first though, as the extension wouldn't show up in the "Manage Trusted Extensions" dialog and the promp to authorize it didn't show up in the menu while logged in either.

**Comment by cschleiden** [comment]
@pluma Oh, which version of VS Code are you using? Insider or the regular one? I had filed a bug on VS Code on this before, but that last time it was due to different scopes.

**Comment by pluma** [comment]
I'm on insider and using WSL. I may have just not seen the menu entry though.

**Comment by iansinnott** [comment]
Thanks @cschleiden, that was it!

The confusion on my part was because I was already signed in to Github when I downloaded the extension, so the error message didn't make sense. Clicking through that account tab resolved it.
