### ISSUE TITLE
Suggestion: use status bar background color API

### ISSUE THREAD

**Issue by inwardmovement** [cschleiden/vscode-github-actions#69]
https://code.visualstudio.com/updates/v1_53#_status-bar-entry-background-color-api

**Comment by cschleiden** [comment]
Nice, I did not know about that!

**Comment by cschleiden** [comment]
Will be included in the next release: 
![image](https://user-images.githubusercontent.com/2201819/107904773-9592ac00-6f01-11eb-89c6-7322a5912853.png)
