### ISSUE TITLE
Key 'defaults' is not allowed

### ISSUE THREAD

**Issue by johnschult** [cschleiden/vscode-github-actions#70]
The linter is finding an issue with the `defaults` keyword in workflows. I am using `v0.16.0` of the extension.

![Screen Shot 2021-02-08 at 8 04 43 AM](https://user-images.githubusercontent.com/9453/107224592-a31dd280-69e5-11eb-9dd9-2b41660f8cda.png)

See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaults

**Comment by johnschult** [comment]
Never mind, I see the problem. The syntax I used is deprecated as a top level keyword.

**Comment by theoribeiro** [comment]
@johnschult Where are you seeing that this will be deprecated? Can't find it anywhere in the docs, am I blind?

**Comment by johnschult** [comment]
What I am saying is that I had defaults in the wrong place. This can be closed.

**Comment by theoribeiro** [comment]
Right, it is closed and I'm having the same issue, hence my question! 😄 

AFAIK having defaults as a top level keyword is a valid config file, isn't it? How did you solve this on your side?

**Comment by cschleiden** [comment]
I think we still support that, probably just missing in the schema the extension uses. Re-opening for investigating.
