### ISSUE TITLE
Incorrect "Invalid Expression" error

### ISSUE THREAD

**Issue by tetchel** [cschleiden/vscode-github-actions#77]
![image](https://user-images.githubusercontent.com/8888438/109018191-e59e0b00-7685-11eb-8d0b-7ffd40a0d8d4.png)

This expression works fine in my workflow runs, so I'm not sure why it is being detected as invalid.

**Comment by tetchel** [comment]
Another incorrect error also just appeared, though you'll note it wasn't there in the screenshot above!

![image](https://user-images.githubusercontent.com/8888438/109019275-d9667d80-7686-11eb-9561-5a9e40934585.png)

**Comment by tetchel** [comment]
Here are two more incorrect errors.

![image](https://user-images.githubusercontent.com/8888438/109025621-e4241100-768c-11eb-9113-15de675bba14.png)

**Comment by icehaunter** [comment]
I also get these errors with "invalid expression" on any function call, and I get those "key is not allowed" errors on local action `with` calls.

**Comment by tetchel** [comment]
Please re-open this!
