### ISSUE TITLE
[INPUT REQUESTED] Support `environments` and `approvals`

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/vscode-github-actions#79]
I want to provide better support for environments and approvals. 

For starters I think seeing a list of environments under the Settings tree, or in a new view would be good. Auto-complete of environments is already available. 

What else would you like to see?

**Comment by JustinGrote** [comment]
Settings tree makes sense, right next to secrets. All in one place would be nice, the Azure Functions extension is a good reference for this IMHO.

Would also like to be able to do polled refresh not just in status bar but in the workflows pane, though I realize this may come with an API rate limit if used too much, maybe just poll the most recent action.

BTW, I love the detachable nature of panes, I put my github actions here:
![image](https://user-images.githubusercontent.com/15258962/112677602-32ad0280-8e27-11eb-9b26-96ac1bd71cf0.png)
