### ISSUE TITLE
Nothing shown

### ISSUE THREAD

**Issue by boredland** [cschleiden/vscode-github-actions#8]
Hi! Sadly I'm not able to use the extension. There seems to be an issue with you having the proposed api flag set in your package.json. I provided a PAT token, but no workflows are shown for my repos. Does it work for organization Repositories?

**Comment by cschleiden** [comment]
Yes, it should. That's how I tested it most of the time. 

What do you mean by

>  There seems to be an issue with you having the proposed api flag set in your package.json.

Do you see any error messages mentioning that?

**Comment by boredland** [comment]
Hi! This gets printed out on my console:
```
'cschleiden.vscode-github-actions cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
```
https://tinyurl.com/t2mu5fn

**Comment by cschleiden** [comment]
Thanks for the log. I don't think I actually use any proposed API, let me double check tonight and publish a new version without that flag. I'll update here.

**Comment by cschleiden** [comment]
@boredland Just published a new version without the proposed flag. Please give it a try.
