### ISSUE TITLE
[Request] Add setting to disable intellisense since the YAML extension with SchemaStore does it better

### ISSUE THREAD

**Issue by JustinGrote** [cschleiden/vscode-github-actions#80]
The latest redhat YAML extension with its auto schemastore for github actions provides far better documentation/completion/intellisense/linting than the current implementation, but having them installed side-by-side leads to duplicate intellisense entries
![image](https://user-images.githubusercontent.com/15258962/112212636-74953900-8bda-11eb-9d43-411209e5e42a.png)

I still really appreciate the "runtime" features of monitoring my github actions statuses without leaving code however. Please add a setting to disable this part of the functionality while preserving the "monitoring" features.

**Comment by krlmlr** [comment]
What extension are you referring to:

- https://github.com/Lona/vscode-github-actions
- https://github.com/formulahendry/vscode-github-actions
- https://github.com/OmarTawfik/github-actions-js
- something else?

**Comment by JustinGrote** [comment]
@krlmlr odd question, obviously referring to this repo...
https://github.com/cschleiden/vscode-github-actions#auto-complete-and-documentation

**Comment by krlmlr** [comment]
Thanks. This means there are at least four alternatives for autocompletion, the RedHat solution being the most generic?

**Comment by JustinGrote** [comment]
@krlmlr both the most generic, and arguably the most accurate since it uses the actual JSON schema produced by the Github Actions team themselves.
