### ISSUE TITLE
feature request: show staus check indicator for current checked out branch

### ISSUE THREAD

**Issue by Thatkookooguy** [cschleiden/vscode-github-actions#84]
When working on a specific branch inside vscode, only show the Pin workflows and see their status updates **for the currently checked out branch**.

This is better for multi-user projects. I want to see the status checks of the work I'm doing atm, and not see what's up when ever a user pushes to a public branch.

I'll try and implement this myself if I'll have the time. thanks for a great extension!

**Comment by Thatkookooguy** [comment]
oh my bad. I see it already works as intended

**Comment by krlmlr** [comment]
Is this handled by https://github.com/grzegorzjudas/vscode-gitbuild?

**Comment by Thatkookooguy** [comment]
please re-open this.

There wasn't any activity since no one really answered. What should I have done without any maintainer saying anything?
