### ISSUE TITLE
Build ID & Polling

### ISSUE THREAD

**Issue by gencer** [cschleiden/vscode-github-actions#9]
First of all, Thank you for this awesome extension. This was the missing part of my workspace and you made it. I was going to make an extension (much smaller one) but after seen this, i will use this one instead of writing it.

Anyway, I have 3 suggestions. 

1. API Rate limit is 5.000 per hour per api key. So, adding polling for 30 seconds or configurable via settings per `x` second will be okay.

2. GitHub recently introduced Build IDs`*` that starts from 1 to count for each workflow. In the past this wasn't possible. So, When i see my builds in your extension i see build ids like `10001510` and etc.. Instead can we use internal build id `1` here?

3. Adding last workflow job status (For example; Running, Failed, Success...) to the statusbar at the bottom to see it. This is also connected to polling request here.`**`

Thanks,
Gencer.

-------

`*` This is what im talking about:
![image](https://user-images.githubusercontent.com/1711576/77539243-18f27b80-6eb2-11ea-863e-f2c8f75cee89.png)

`**` Added third suggestion.

**Comment by cschleiden** [comment]
> Adding last workflow job status (For example; Running, Failed, Success...) to the statusbar at the bottom to see it. This is also connected to polling request here.**

Has been included in v0.3.0, give it a try :)

**Comment by gencer** [comment]
Thank you, @cschleiden!
