### ISSUE TITLE
`runs-on` throw's error when given an expression

### ISSUE THREAD

**Issue by nodeselector** [cschleiden/vscode-github-actions#92]
I expect the linter to not have any issues with this playbook:
![image](https://user-images.githubusercontent.com/29457092/119218378-c3edcd80-ba94-11eb-9f37-c3e30c6b9e2f.png)

However, strangely enough, if a second matrix expression is added the linter is satisfied:
![image](https://user-images.githubusercontent.com/29457092/119218406-fdbed400-ba94-11eb-83b1-e8caac94722d.png)

**Comment by cschleiden** [comment]
Closing as a duplicate of https://github.com/cschleiden/vscode-github-actions/issues/104 (more context there)
