### ISSUE TITLE
Can't figure out how to authenticate with github

### ISSUE THREAD

**Issue by bryanhuntesl** [cschleiden/vscode-github-actions#94]
This is probably just me being foolish. 

The 'workflows pane' displays the message 'Please sign-in in the Accounts menu.' but I don't see an accounts menu and can't find one in the VS Code UI. Do I need to install another plugin to get this to work? 

https://github.com/cschleiden/vscode-github-actions/blob/acf24282993e132e1d481115061f1a0b8a2e58a5/src/treeViews/workflows.ts#L24

**Comment by bryanhuntesl** [comment]
Ok, that's VS Code's UX, not yours - I didn't notice the accounts icon down at the bottom of the page. 

<img width="380" alt="Screenshot 2021-05-25 at 17 39 36" src="https://user-images.githubusercontent.com/31992054/119535778-4a016100-bd80-11eb-960e-d3973dbbc0b0.png">

**Comment by japgolly** [comment]
Lifesaver! Thanks for posting the solution @bryanhuntesl ! I had the same problem
