### ISSUE TITLE
Support for GH Enterprise

### ISSUE THREAD

**Issue by florian30491** [cschleiden/vscode-github-actions#95]
Reopening an issue, because issue #58 were closed.

**Comment by silkfire** [comment]
@cschleiden What's the status on this?

**Comment by Paul-AUB** [comment]
I'm also very interested by this feature !

**Comment by sm1rnoff** [comment]
does it support GHES integration? 
following...

**Comment by doyou89** [comment]
[vscode pull request and issues extension](https://github.com/Microsoft/vscode-pull-request-github) now supports GH enterprise using "GitHub Enterprise Authentication Provider".
Please check this method.

**Comment by nicola-lunghi** [comment]
Hi can you be more specific?

**Comment by cschleiden** [comment]
We are looking at providing support for GitHub Enterprise. I don't have a date yet but we've been talking to the maintainers of the PR extension.

**Comment by cschleiden** [comment]
This is now tracked here: https://github.com/github/vscode-github-actions/issues/12
